### ISSUE TITLE
Problems with the API

### ISSUE THREAD

**Issue by Fenaudi** [MELVARDEV/League-Pass-Manager#14]
Hey, first i love your Project.
I use it now for over a Year without Issues.
But now i have Problems with the API. I saw you wanna redesign the App or smth and you updated a few things.
How can i use this to Fix my API Problems on my local Programm?

**Comment by MELVARDEV** [comment]
Hi and thanks a lot, I haven't had much time to work on the project recently and in meantime there were some API changes made by Riot Games that might have broken the current version of the app (such as the change from summoner names to Riot ID). I will probably update the old version of the app and the API to support the new format in the coming days.

**Comment by MELVARDEV** [comment]
Hi again, I have updated the API and the app to use the new endpoints. You can download it here:
https://github.com/MELVARDEV/League-Pass-Manager/releases/tag/v2.2.0-alpha

Very important, please make sure that you back up the "accounts" file and all your data before trying to replace the app with the new version. 
Once you run the app, there will be one more field to add to each account, that is Tag Name / Riot ID. For the account information this is a required field now.

Please let me know if the app works and if there are any new issues because of the update.

**Comment by Fenaudi** [comment]
Hello, the API works now. Thanks for your fast Fix.
The new Emerald Rank have no Icon. Not sure if this is easy to add.
The Auto Login isnt working but this is not a big Deal.

**Comment by MELVARDEV** [comment]
Hi, I'm glad the API works and thanks for the feedback.
The emerald icon should be easy to add so I'll look into it and I'll check up on the autofill since it should be a fairly easy fix too.
I'll close this issue for now since It's was related to the API.
